export enum TaskStatus {
  DRAFT = 'DRAFT',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  DENIED = 'DENIED',
  SUBMITTED = 'SUBMITTED',
  APPROVED = 'APPROVED',
  REOPENED = 'REOPENED',
}

export enum UserRole {
  ADMIN = 'ADMIN',
  EMPLOYEE = 'EMPLOYEE',
}

export enum NotificationEvent {
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_DENIED = 'TASK_DENIED',
  TASK_ACCEPTANCE_OVERDUE_EMPLOYEE = 'TASK_ACCEPTANCE_OVERDUE_EMPLOYEE',
  TASK_ACCEPTANCE_OVERDUE_MANAGER = 'TASK_ACCEPTANCE_OVERDUE_MANAGER',
  TASK_SUBMITTED = 'TASK_SUBMITTED',
  TASK_APPROVED = 'TASK_APPROVED',
  TASK_REOPENED = 'TASK_REOPENED',
}

export const ACCEPTANCE_OVERDUE_HOURS = 24;
export const REFRESH_TOKEN_EXPIRES_DAYS = 7;
